### PR TITLE
Finalize validation for running MC

### PR DESCRIPTION
**Pull request by dberzano**
The purpose of this PR is to finalize the work done so far to run locally (local computer, local batch resources) a MC production. This is, in turn, necessary for validating AliRoot releases.

The ultimate purpose is to run the entire reconstruction-to-filtering workflow on raw data too, but first let's see what we are missing for Monte Carlos.

What works:

* Output both on local directory and XRootD (authenticated too, and robust - with smart retries on errors)
* Continues also if some jobs fail
* Correct propagation of environment variables as in the real JDL
* Works with Work Queue and also locally (possible to run it effortlessly on our validation cluster, drop-in replacement to the current one)
* Supports zipping of output files (can be disabled optionally), same as the Grid
* AliDPG + AliRoot support CVMFS OCDB: alisw/AliDPG#31, alisw/AliRoot#232, alisw/AliRoot#278

**Note that at least AliRoot v5-09-10 is required for this to work.**

I have a checklist I wanted to verify with the tagged persons.

- [x] Verify the content of README.md in this pull request (is the workflow description correct?)
- [x] Grab a second example of a JDL from a recent production from @catalinristea
- [x] Try to run such example
- [x] Determine a good MC example to run systematically for the Release Validation (we've never converged there!)

You can find the output of this example on EOS:

* [Full output on MC run](https://ali-ci.cern.ch/release-validation/montecarlo_test/)
* [QA plots](https://ali-ci.cern.ch/release-validation/montecarlo_test/QAplots_passMC) _(note: only ITS and TPC enabled)_

You can find the output of this example on EOS (there were only 32 jobs with one event each, so QA plots just have insufficient data, I guess). Since Makeflow supports that, I am also attaching [a PDF file with the workflow schema](https://github.com/alisw/release-validation/files/1683831/iTerm2.VJS1fi.file.pdf) (check the green ellipses).

I really want to be sure that this is what we are running on the Grid.

I also have a general doubt about the directory structure used for storing QA plots on Monte Carlos. I seem to understand the path for each detector is:

    <detector>/<year>/<period>/passMC/<run>

leading to paths like:

    ITS/2016/LHC16h8a/passMC/000244411

is this correct?

### CODE REVIEW

**Comment by dberzano** [comment]
Adding @catalinristea, @chiarazampolli and @fprino to the conversation.

**Comment by chiarazampolli** [comment]
Ciao @dberzano , 

Yes, the directory is called like that but what is merged is the FilteredTrees of the TPC, which is something different. I think - for the sake of curiosity - that the directory is called like that because at the beginning the idea was to use the FilteredTrees for the SpacePointCalibration. Bad name now... But to change in production could possibly break something - if anything is using these files.

Thanks!

Chiara

**Comment by dberzano** [comment]
[Here's](https://ali-ci.cern.ch/release-validation/gpmc001) the output from the GPMC. I would say, we are now ready to run MCs from JDLs locally, i.e. we can use them for the release validation! A couple more minor steps are required before proceeding (fixing the README and add a JDL parsing feature), but after that we can consider closed this chapter and move to the next and last: supporting the full data workflow on validation.

**Comment by chiarazampolli** [comment]
Thanks Dario, this is great!
Chiara

**Pull request merged**
