### PR TITLE
[WIP] Fit MC release validation into Jenkins

### PR DESCRIPTION
**Pull request by dberzano**
This pull request is used to keep track of the development effort to make jdl2makeflow compatible with the current Jenkins jobs.

- [x] Simplify XML dependency
- [x] Add support for AliDPG validation
- [x] Override packages via custom command
- [x] Silence stderr/stdout of every job in Makeflow (no `tee`, we have logfiles after all)

### CODE REVIEW

**Comment by dberzano** [comment]
@catalinristea @chiarazampolli @fprino fyi - this PR is merely technical and does not require your input. Just for you to know: I am integrating AliDPG into the release validation, in a way that we can validate AliDPG releases too before tagging.

**Comment by dberzano** [comment]
Note that alisw/ali-bot#537 is needed too.

**Comment by dberzano** [comment]
This integration round seems to be complete. Currently testing it on Jenkins, [here](https://alijenkins.cern.ch/job/AliRootDPGValidation/59/console).

**Note:** after merging this PR, it will be impossible to run the "old" release validation from master. We are changing the Jenkins job to point the old job to a legacy branch.

**Comment by dberzano** [comment]
OK we can finally and safely claim that we are now fully able to validate:

* Monte Carlos
* AliDPG

Merging this one!

**Comment by dberzano** [comment]
Next, and final, step is: running raw data processing.

**Comment by chiarazampolli** [comment]
Ciao Dario,
Very good! Let me know if you need any help with data processing!
Chiara
PS. when you say that we can run with AliDPG, this means only MC - I specify this for the sake of clarity.

**Pull request merged**
