### PR TITLE
Add DPG experts to the JIRA relval notifications

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@fprino do you have somebody else who should be added for DPG? This is the JIRA notification for the release validation.

**Comment by fprino** [comment]
Hi Dario,

Chiara is already in the list of notified people, right?

Cheers, Francesco

**Comment by dberzano** [comment]
She is, for the "Calibration" group. I have added the "DPG" group with you only. Let me know if this is OK (or if we should add Michael too).

**Comment by fprino** [comment]
Hi Dario,

indeed, in view of adding in the future the validation on MCs it would be good to have also Michael and Catalin.

Cheers, Francesco

**Comment by dberzano** [comment]
What are their CERN usernames? mweber, cristea?

**Comment by fprino** [comment]
Hi,

in  github, they are @miweberSMI and @catalinristea.
Not sure if this helps you to extract their CERN usernames.

Ciao, Francesco

**Comment by catalinristea** [comment]
Hi,

I think both would work, because we had AliDPG before the migration to GitHub and I had already a GitHub account. After the migration, I did also linked the CERN account with GitHub, so cristea would work.
Thanks!

Yours,
Catalin.

**Comment by dberzano** [comment]
Since these are the JIRA notifications, I am going to use your CERN usernames (I have found them in our internal GitHub-to-CERN mapping).

There is now a DPG group in JIRA mentioning @fprino, @miweberSMI and @catalinristea. This will be effective from the next release validation.

Thanks!

**Pull request merged**
